"""
Degree distribution of weight matrices: baseline vs. weight decay vs. Omega-S.

This is the figure that makes the paper's central concept visible. It is not
generated by `make_figures.py` because it requires the trained weight matrices,
which are not redistributed with this repository. Run it after a local
fine-tuning run.

What it shows
-------------
Omega-S is defined by what it does to the distribution of row norms, that is,
the degree sequence of the weight graph. The headline number in Section 4.2 is
a reduction in degree variance from 41.94 to 0.136, an order of magnitude
beyond what weight decay achieves at matched accuracy. A histogram of the row
norms makes that concrete: weight decay shifts the whole distribution toward
zero without changing its shape, whereas Omega-S contracts its spread.

Usage
-----
    python figures/degree_distribution.py \\
        --baseline runs/baseline/adapter_model.safetensors \\
        --wd       runs/weight_decay/adapter_model.safetensors \\
        --omega    runs/omega_s/adapter_model.safetensors \\
        --layer    model.layers.16.self_attn.q_proj

Any checkpoint format readable by `safetensors` or `torch.load` works; the
script only needs the weight matrix of one layer from each run. Use the same
layer for all three, and prefer a mid-network attention projection, where the
effect reported in Section 4.2 is largest.
"""
from __future__ import annotations
import argparse

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

plt.rcParams.update({"font.size": 9, "axes.spines.top": False,
                     "axes.spines.right": False, "figure.dpi": 200})
BLUE, RED, GREY = "#1f4e79", "#c0504d", "#7f7f7f"


def load_matrix(path: str, layer: str) -> np.ndarray:
    """Return the effective weight matrix of `layer` from a checkpoint."""
    if path.endswith(".safetensors"):
        from safetensors.numpy import load_file
        sd = load_file(path)
    else:
        import torch
        sd = {k: v.float().cpu().numpy()
              for k, v in torch.load(path, map_location="cpu").items()}

    exact = [k for k in sd if k.endswith(layer + ".weight")]
    if exact:
        return np.asarray(sd[exact[0]], dtype=float)

    # LoRA checkpoint: reconstruct the delta B @ A for this layer
    a = [k for k in sd if layer in k and "lora_A" in k]
    b = [k for k in sd if layer in k and "lora_B" in k]
    if a and b:
        return np.asarray(sd[b[0]], dtype=float) @ np.asarray(sd[a[0]], dtype=float)

    raise KeyError(f"layer {layer!r} not found in {path}; "
                   f"available keys include {list(sd)[:5]}")


def degrees(W: np.ndarray) -> np.ndarray:
    """Degree of each output unit: the L1 norm of its row."""
    return np.abs(W).sum(axis=1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", required=True)
    ap.add_argument("--wd", required=True)
    ap.add_argument("--omega", required=True)
    ap.add_argument("--layer", required=True)
    ap.add_argument("--out", default="figure2_degree_distribution")
    args = ap.parse_args()

    runs = [("baseline", args.baseline, GREY),
            ("weight decay", args.wd, RED),
            ("Omega-S", args.omega, BLUE)]

    fig, ax = plt.subplots(1, 2, figsize=(9.0, 3.4))
    stats = []

    for name, path, colour in runs:
        d = degrees(load_matrix(path, args.layer))
        stats.append((name, d.mean(), d.var()))
        ax[0].hist(d, bins=60, histtype="step", lw=1.6, color=colour, label=name)
        ax[1].plot(np.sort(d)[::-1], lw=1.6, color=colour, label=name)

    ax[0].set_xlabel("degree (row $L_1$ norm)")
    ax[0].set_ylabel("units")
    ax[0].set_title("(a) Degree distribution", fontsize=9.5, loc="left")
    ax[0].legend(frameon=False, fontsize=8)

    ax[1].set_xlabel("unit, ranked")
    ax[1].set_ylabel("degree")
    ax[1].set_yscale("log")
    ax[1].set_title("(b) Ranked degree, log scale", fontsize=9.5, loc="left")

    caption = "   ".join(f"{n}: Var = {v:.3g}" for n, _, v in stats)
    fig.suptitle(caption, fontsize=8.5, y=0.02, color="0.35")
    fig.tight_layout()
    fig.savefig(args.out + ".png", bbox_inches="tight")
    fig.savefig(args.out + ".pdf", bbox_inches="tight")

    print(f"{args.out} written")
    for n, m, v in stats:
        print(f"  {n:14s} mean {m:.4g}   variance {v:.4g}")


if __name__ == "__main__":
    main()
